manubot/rootstock

build/authors.py, content/00.front-matter.md, content/authors.tsv
Put checks in for Name and initials to be required. Add in conditional… formatting if fields are missing.
=> Fix formatting of missing author fields #15

ci/deploy.sh
Deployment was failing due to https://github.com/travis-ci/travis-ci/issues/8082
=> Workaround for Travis timeout / termination

ci/deploy.sh
Follows up on the unsuccessful https://github.com/greenelab/manubot-rootstock/pull/19
Addresses https://github.com/travis-ci/travis-ci/issues/8082
Attempt to fix build error https://travis-ci.org/greenelab/manubot-rootstock/builds/254181411#L1379
=> Second attempt for Travis deploy timeout

build/build.sh
Follows up on https://github.com/greenelab/manubot-rootstock/pull/26
https://stackoverflow.com/a/3411105/4651668
=> Fix sh error when BUILD_DOCX=true

build/build.sh, build/references.py, content/00.front-matter.md
This adds a date in both the HTML `<head>` like:
```html
<meta name="date" content="2017-07-20">
```
And prints the date in the output like either:
> This manuscript was automatically generated on July 20, 2017.
Or if via a Travis master build:
> This manuscript was automatically generated from greenelab/manubot-rootstock@xxXXxxX on July 20, 2017.
=> Add date to output

references/README.md
=> Add in link for additional examples. Fix issues #28.

build/environment.yml
Fixes issue where manual references were not respected.
=> Upgrade manubot version

build/build.sh, build/environment.yml
Closes https://github.com/greenelab/manubot-rootstock/issues/55
Also reorder some pandoc CLI arguments.
=> Add --mathjax to pandoc build

.gitmodules, build/environment.yml, ci/deploy.sh
Closes https://github.com/greenelab/manubot-rootstock/issues/59
=> Switch OpenTimestamps from submodule to pip

README.md, build/autobuild.sh, build/build.sh, build/environment.yml
Refs https://github.com/greenelab/manubot-rootstock/issues/58#issuecomment-325056265
@slochower any suggestions?
=> Autobuild: watchdog monitor content dir

README.md
=> Note MIT licensed 3rd-party code

USAGE.md, build/build.sh, build/environment.yml
Closes https://github.com/greenelab/manubot-rootstock/issues/77
=> PDF export: use weasyprint not wkhtmltopdf

content/00.front-matter.md
Attempt to fix warping of the images in docx.
=> Add in width to images to better size images and fix warping

USAGE.md
See discussion at https://github.com/greenelab/manubot-rootstock/pull/81#discussion_r148344009
=> USAGE.md: link to language tag documentation

SETUP.md, build/README.md
Work in progress.
Thanks @zambujo @RaoOfPhysics @broadwym @schliebs @Hillea and others who've stopped by our OpenCon Do-A-Thon table. See https://github.com/sparcopen/doathon/issues/21 for more info.
Attendees have begun setting up manuscripts. We've noticed some pain points and difficulties. This PR aims to improve the `SETUP.md` documentation in response to these issues.
Feel free to review this PR or make additional doc suggestions.
=> Update SETUP.md based on OpenCon do-a-thon

.travis.yml, build/environment.yml
Update depedencies to latest versions
Update minoconda to 4.3.30:
https://github.com/conda/conda/blob/c72c237a354c3fd9629d800311ba6a2b8a95d1d1/CHANGELOG.md#4330-2017-10-17
Update pandoc to 2.0.4:
https://github.com/jgm/pandoc/releases/tag/2.0.4
Update cairo to 1.14.10:
https://cairographics.org/news/cairo-1.14.10/
Update cffi to 1.11.2:
https://cffi.readthedocs.io/en/latest/whatsnew.html#v1-11-2
Update jinja2 to 2.10:
http://jinja.pocoo.org/docs/2.10/changelog/#version-2-10
manubot update to support multiple --template-variables-path args
=> Update environment.yml on 2017-12-04

.travis.yml, README.md, USAGE.md, build/README.md, build/environment.yml, content/00.front-matter.md, content/02.delete-me.md, content/metadata.yaml
=> Maintenance updates on 2018-01-09

README.md
Add issue guidelines per @michaelmhoffman suggestion in greenelab/manubot#29.
Closes https://github.com/greenelab/manubot/issues/29
=> Suggest issues for general inquiries

build/environment.yml
Should upstream fix issues:
Extra brackets around citations in figure captions
https://github.com/jgm/pandoc/issues/4272
WeasyPrint 0.42 gets stuck
https://github.com/Kozea/WeasyPrint/issues/560
Updated pandoc-xnos with better semantic versioning
https://github.com/tomduck/pandoc-fignos/issues/46
=> Update environment on 2018-02-06

USAGE.md
As suggested in https://github.com/greenelab/meta-review/issues/45#issuecomment-401613937
@vsmalladi can you review?
=> Usage examples: add TFSEE

webpage/github-pandoc.css
Closes https://github.com/greenelab/manubot-rootstock/issues/130
I'm far from a proficient CSS developer, so please double check whether what I'm doing makes sense.
Have not tested yet.
=> CSS: table, figure, caption alignment

.travis.yml, USAGE.md, build/environment.yml
TODO: https://github.com/greenelab/manubot/issues/59 and acknowledge Sloan funding
=> Update environment on 2018-10-08

build/environment.yml
Includes migration of PMCID citations to Literature Citation Exporter.
=> Update manubot to v0.2.1 with PMCID fix

SETUP.md
Addresses workflow error in https://github.com/greenelab/deep-review/pull/939#issuecomment-439220820
=> SETUP.py: add checkout command to rootstock upgrade

.travis.yml, SETUP.md, build/environment.yml
The `sed` command in `SETUP.md` was not using the appropriate random string in `deploy.sh`.
=> Update SETUP.md to replace the correct random string

build/themes/default.html
See file diff for changes. Too many and small changes to list here.
Hold off on merging this until plugins PR is finalized, in case I make more small adjustments to this.
=> Various aesthetic updates

build/plugins/accordion.html, build/plugins/jump-to-first.html, build/plugins/lightbox.html, build/plugins/link-highlight.html, build/plugins/table-of-contents.html, build/plugins/tooltips.html, build/themes/default.html
closes #199 
closes #202 
closes #197
=> minor theme improvements and plugin fixes

.travis.yml, build/build.sh
Closes https://github.com/manubot/rootstock/issues/170
More information about Athena is available at
https://github.com/arachnys/athenapdf
Apply feature from meta-review commit:
https://github.com/greenelab/meta-review/commit/cffcfeaea0b6859051d16ab1e263d8bcf62a24b1
This commit was created with the command:
```
curl https://github.com/greenelab/meta-review/commit/cffcfeaea0b6859051d16ab1e263d8bcf62a24b1.patch | git apply
```
=> Use Athena to build PDF, if Docker is installed

USAGE.md, content/02.delete-me.md
Also update URLs in `02.delete-me.md`
=> Add links to PLOS Comp Bio article on Manubot

.appveyor.yml, USAGE.md, build/README.md, build/environment.yml, content/00.front-matter.md
Closes https://github.com/manubot/rootstock/issues/176
Closes https://github.com/manubot/rootstock/issues/267
=> Set extra <meta> fields in HTML <head>

content/00.front-matter.md
Fixup f1bf210b115607b1887c0dcfaed11cbe81543967
=> Fixups following HTML <meta> and variables update

.github/workflows/manubot.yaml, .travis.yml, SETUP.md, ci/deploy.sh
Not sure yet which parts of this we want to keep
=> Change CI behavior when MANUBOT_SSH_PRIVATE_KEY is unset

.appveyor.yml
Hopefully addresses some of the issues here: https://github.com/czbiohub/orthology-free-comparative-transcriptomics-paper/pull/47/ and https://github.com/manubot/rootstock/issues/308
=> Add note in .appveyor.yml about skipping branches with PR

build/environment.yml, content/metadata.yaml
Includes manubot update with yamllint support
=> Update environment on 2020-02-17

USAGE.md, build/environment.yml
=> Update environment and usage on 2020-02-27

.github/workflows/manubot.yaml
https://help.github.com/en/actions/configuring-and-managing-workflows/caching-dependencies-to-speed-up-workflows#using-the-cache-action
=> GitHub Actions: enable caching

SETUP.md
Minor word changes that would have helped clarify things for me -
* OWNER can be an organization!
* no additional configuration is needed for github actions.
(I got everything up and running with no additional effort, but I took a flyer on these two things - glad it worked, but these mods maybe help future me!)
=> suggested wording updates to rootstock SETUP.md

build/build.sh
closes https://github.com/manubot/rootstock/issues/368
https://stackoverflow.com/a/55283209/4651668
https://stackoverflow.com/a/18035947/4651668
=> build.sh: skip docker when installed but not running

build/plugins/math.html
closes #377
Reference: https://cdnjs.com/libraries/mathjax/2.7.5
=> fix mathjax loading error

build/README.md, build/environment.yml
Hold back pandoc due to panflute support.
=>  Upgrade environment on 2020-10-30

build/build.sh, build/pandoc/defaults/latex.yaml
refs https://github.com/manubot/rootstock/issues/249
=> Export basic LaTeX manuscript

content/00.front-matter.md
closes https://github.com/manubot/rootstock/issues/437
=> Explicitly define front matter icon dimensions

.github/workflows/manubot.yaml
https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/
=> CI: boolean inputs for workflow dispatch

.github/workflows/manubot.yaml
add SPELLCHECK & MANUBOT_USE_DOCKER options.
=> CI: more workflow_dispatch options

build/environment.yml
Includes Python 3.11 & Pandoc 2.18
=> Upgrade environment on 2022-11-22

USAGE.md, content/00.front-matter.md, content/images/mastodon.svg, content/metadata.yaml
merges https://github.com/manubot/rootstock/pull/483
=> author/frontmatter: mastodon links

build/environment.yml
refs https://github.com/manubot/rootstock/pull/512#issuecomment-2233955723
=> Manubot upgrade on 2024-07-20

.github/workflows/ai-revision.yaml
This is a simple PR that updates to the lates OpenAI model, `gpt-4o`.
=> ai-revision: update to latest OpenAI model
