manubot/rootstock

- README.md
While working through the process outlined in #6 I noticed the short URLs still pointed to deep-review
> Update shortened URLs

- build/build.sh
Fixes issue reported in https://github.com/greenelab/deep-review/pull/569 where some OSes use a non-UTF-8 default encoding.
CC @yfpeng
> Use same locale for all builds

- build/citations.py
Full error:
```
pandoc-citeproc: Error in $[26].categories[0][0]: failed to parse field categories: mempty
CallStack (from HasCallStack):
error, called at src/Text/CSL/Input/Bibutils.hs:50:49 in pandoc-citeproc-0.10.4-36ROWpY3Inr1fCxMvEajRL:Text.CSL.Input.Bibutils
pandoc: Error running filter pandoc-citeproc
```
> Fix citeproc issue with catagories

- build/references.py
- content/00.front-matter.md
Only applies to manuscripts built on Travis. Creates a header under the title with version information. Therefore, given a manuscript that's built via Travis, you can always get back to the source:
Also will help alert readers to the online source and manubot system.
> Write source repo version info in manucript

- build/references.py
- content/00.front-matter.md
- content/metadata.yaml
I think our keys for author information were too verbose, especially since the YAML format requires lot's of repetition of these keys.
Since all changes to existing keys in `metadata.yaml` are breaking changes for manubot instances, we should do them sooner rather than later.
> Shorten & simplify metadata author keys

- .gitignore
- build/build.sh
- build/references.py
Thanks @tarleb for the tip, which I couldn't find in the pandoc docs. This is a much preferable to sed. Especially since it works for DOCX output!
> Use meta-author / meta-date to remove sed

- build/build.sh
- output/github-pandoc.css
Closes https://github.com/greenelab/manubot-rootstock/issues/38
With this PR, here's what the PDFs look like:
+ generated in `build.sh`: [manuscript-wkhtmltopdf.pdf](https://github.com/greenelab/manubot-rootstock/files/1166592/manuscript-wkhtmltopdf.pdf)
+ print preview in chrome on linux [manuscript-chrome-linux.pdf](https://github.com/greenelab/manubot-rootstock/files/1166598/manuscript-chrome-linux.pdf)
Note that I added a section (not tracked) with lorem ipsum text.
Also `--print-media-type` gets rid of border from the `wkhtmltopdf` PDF.
> Set print margin-top and margin-bottom

- build/references.py
Having a word count would be a convenience for anyone writing a manuscript that imposes word limits.  It is not obvious what should be counted.  For now, I count all whitespace-separated strings after rendering the Jinja2 templates.
The build output is:
```
Using metadata cache: True
3 unique citations strings extracted from text
2 unique citations after standardizations
standard_citation                 text
doi:10.1101/142760  @doi:10.1101/142760
doi:10.1101/142760     @tag:deep_review
References by type:
Counter({'total': 2, 'doi': 1, 'url': 1})
Word count: 323
Exporting HTML manuscript
Exporting PDF manuscript
```
If I copy and paste the HTML into Word, it gives a count of 306.  Word might be ignoring figures and tables, but I didn't probe the cause.
> Add word count

- USAGE.md
- build/build.sh
- build/environment.yml
Closes https://github.com/greenelab/manubot/issues/3
Specifying `TZ` in `build.sh` rather than `.travis.yml`, has the benefit of effecting local builds as well.
Tagging @slochower
> Set timezone to UTC in build.sh

- SETUP.md
- build/environment.yml
- content/99.back-matter.md
Rebase #65 once this is merged.
> SETUP.md updates and Manubot version bumb

- webpage/github-pandoc.css
Newlines make it easier to edit the ` /* Github css */` section. For example, see https://github.com/dhimmel/rephetio-manuscript/commit/c78f9ad09d063982a1668a285b2fdf7b14c9df05
> Prettify github-pandoc.css

- content/99.back-matter.md
Enables content that follows the bibliography
From https://github.com/jgm/pandoc-citeproc/blame/5a7f26b61c8577916093851cdeb31fa9a198edcb/man/pandoc-citeproc.1.md#L126-L128
> a bibliography will be inserted into each Div element with id refs. If there is no such Div, one will be created at the end of the document.
> Explicitly insert bibliography

- build/assets/style.csl
Simplify the CSL specification as per https://github.com/greenelab/manubot-rootstock/issues/53.
The two issues I can't resolve are:
1. Hyperlinking titles. Unfortunately, the [CSL docs](http://docs.citationstyles.org/en/stable/specification.html) don't mention the option to use a URL as a hyperlink. I'm guessing that hyperlinks are not a feature of CSL.
2. Making author names lighter or smaller.
They're not deal-breakers but would be nice.
You can see what this style currently looks [like here](https://github.com/dhimmel/rephetio-manuscript/blob/def8b4602260b38d27bb4b60d54c179fc03ee3cb/manuscript.pdf):
> ![bibliography](https://user-images.githubusercontent.com/1117703/30039878-070c6b8e-91a5-11e7-8820-dc847eb46760.png)
> Customize Manubot citation style

- .travis.yml
Do not use latest miniconda, since updates can cause bugs, which happened at https://github.com/greenelab/manubot-rootstock/pull/75#issuecomment-332914877. [Solution](https://stackoverflow.com/a/46457813/4651668) by @jriehl:
> It looks like Anaconda had a new release (4.3.27) that sets the C compiler path to a non-existing executable (quite an embarrassing bug; I'm sure they'll fix it soon). I had a similar issue with pip installing using the latest Miniconda, which I fixed by using the 4.3.21 version and ensuring I was not doing something like `conda update conda`.
> Pin miniconda version

- USAGE.md
- build/build.sh
- build/environment.yml
- content/metadata.yaml
Pandoc upgraded to v2.0.0.1.
Swap anaconda packages to conda-forge.
> Update environment and documentation

- USAGE.md
- build/environment.yml
`pmcid` citations are higher suggested priority than `pmid` citations, because I think it's likely that the NCBI Citation Exporter will return higher quality metadata with greater reliability than our E-Utilities to CSL functionality.
Upgrade Manubot to https://github.com/greenelab/manubot/commit/b53f487026954729ce80ca963f3838ebca85a144
Refs https://github.com/greenelab/manubot/pull/24
> Enable PubMed ID citations

- build/environment.yml
Pinning pandoc-eqnos, pandoc-fignos, and pandoc-tablenos, but allowing them to trigger the installation of the latest pandoc-xnos version (which is a dependency) caused issues. See https://github.com/greenelab/deep-review/pull/774#issuecomment-357520693.
Thanks @tomduck for helping us diagnose the issue.
> environment: explicitly set pandoc-xnos version

- build/environment.yml
Upgrade Manubot with citations.tsv error message improvements (refs https://github.com/greenelab/manubot/issues/26).
Upgrade to weasyprint v0.42
http://weasyprint.readthedocs.io/en/latest/changelog.html#version-0-42
> Environment updates on 2018-01-14

- USAGE.md
Per https://github.com/greenelab/deep-review/issues/699#issuecomment-358079022 I believe `=` requires a citation tag and would like to document this.
> Update usage instructions for citation tags

- webpage/github-pandoc.css
Closes https://github.com/greenelab/manubot-rootstock/issues/105
At least for the Sci-Hub manuscript this change increased the length (number of pages). See the letter manuscript at [manuscript.pdf](https://github.com/greenelab/manubot-rootstock/files/1685322/manuscript.pdf).
> Changing to letter by default seems okay. In the usage we can note or link to instructions for setting it back to A4.
@agitter going to skip adding instructions to USAGE, since I'm not sure of our longterm plans regarding the CSS and how it should be edited. Also hopefully users will be able to now more easily search for https://github.com/greenelab/manubot-rootstock/issues/105 if they're curious.
> Webpage: specify letter page size in CSS

- ci/deploy.sh
git's user.name config was being set to first names only, since names are space separated. Add quotes to prevent this.
example before:
```
$ git log
commit 8b6861af46df7ec2664aca2d2d5e08a0bf3bb238 (HEAD -> gh-pages, upstream/gh-pages)
Author: Daniel <daniel.himmelstein@gmail.com>
Date:   Wed Jan 24 18:34:49 2018 +0000
```
> Fix name with space issue

- README.md
- build/autobuild.sh
Most autobuild users will want to automatically update the webpage. See discussion at
https://github.com/greenelab/manubot-rootstock/pull/101#issuecomment-366405495
Update README to better document autobuild.
@slochower can you take a look and confirm that this does what you want it to?
> autobuild.sh: include webpage.py execution

- .travis.yml
The method for enabling conda has changed. See [4.4 release notes](https://github.com/conda/conda/blob/53954c0d6785510587cd755a0cee4e177dca8455/CHANGELOG.md#recommended-change-to-enable-conda-in-your-shell).
Refs https://github.com/greenelab/manubot-rootstock/pull/97#discussion_r160516479
> Upgrade miniconda on Travis to 4.4.10

- content/00.front-matter.md
The preambles were getting a bit long. For example, see https://greenelab.github.io/scihub-manuscript/v/8e538a98e4f16bab632c00efb1fb4f1b23a1c122/
> ![not-brevity](https://user-images.githubusercontent.com/1117703/36688167-979b7086-1af9-11e8-955a-17504f7b3879.png)
> front matter: hyperlink permalink for brevity

- build/assets/style.csl
Change style of citations from [1–4] to [1,2,3,4]
Part of https://github.com/greenelab/manubot-rootstock/issues/118
Refs https://github.com/citation-style-language/schema/issues/150
Thanks @rmzelle for the tip how to make this change!
> CSL: do not collapse numeric citations

- build/build.sh
Refs https://github.com/greenelab/manubot-rootstock/issues/120
CC @adebali @vsmalladi
> build.sh: remove long args incompatible with macOS

- .travis.yml
- build/assets/style.csl
- build/build.sh
- build/environment.yml
> Upgrade manubot & environment on 2018-08-22

- build/assets/style.csl
Addresses issue at https://github.com/greenelab/manubot/pull/58/commits/6efe572edcff8e88d13556e5c831bbe1f9400827#r220241077
Hopefully can also address [this](https://github.com/greenelab/manubot-rootstock/pull/132#discussion_r212458417):
> is it easy to add a default value when there is no author? I'll open a separate issue if it is out of scope.
> CSL: improve whitespace in references

- SETUP.md
Closes #137 
Based on some quick testing with the URLs, I believe GitHub is not case-sensitive but Travis is.
> Case sensitive environment variables

- build/environment.yml
Updates Manubot to fix empty date-parts issue.
Downgrades opentimestamps and python-bitcoinlib to resolve incompatible version issue detected by pip.
Closes https://github.com/greenelab/manubot-rootstock/issues/136
> Update environment on 2018-10-23

- USAGE.md
- build/environment.yml
- content/02.delete-me.md
`manubot process` now supports raw citations as per https://github.com/greenelab/manubot/issues/62
> Enable raw citations & small USAGE updates

- build/README.md
- build/environment.yml
Closes https://github.com/greenelab/manubot-rootstock/issues/144
pango is required by WeasyPrint during the PDF build. While usually built-in to the OS on Linux, it is not pre-installed on macOS. macOS were installing pango using homebrew, which led to a segmentation fault error.
Pango is available on conda-forge for linux and mac:
- https://anaconda.org/conda-forge/pango
- https://github.com/conda-forge/pango-feedstock
Adding pango to environment.yml prevents conda environment installation on Windows, but has the benefits of standardizing the pango version on linux and mac platforms and preventing the mac homebrew issue.
> Add pango to conda environment

- build/webpage.py
- ci/deploy.sh
- webpage/README.md
I was mistaken in the past when I though upgrading a timestamp required a local Bitcoin node. That is not the case, only verifying a timestamp requires a node. Upgrading refers to adding information to the `.ots` file that connects the merkle tree root returned by the calendar to a bitcoin block header.
I had put off making this change due to https://github.com/opentimestamps/opentimestamps-client/issues/71, but I decided we should just do our own workaround, since the timestamps have a much larger trust-model until upgraded.
> webpage utility: attempt to upgrade timestamps

- content/00.front-matter.md
Modify the jinja2 front-matter template logic to omit adding author metadata that is `None` (for `orcid`, `github`, and `twitter`) or an empty list (for `affiliations` and `funders`). See https://github.com/dhimmel/psb-manuscript/pull/18#discussion_r245631421 for the initial bug report.
I tested the changes with the PSB Manuscript. [Before](https://git.dhimmel.com/psb-manuscript/v/357d509102adcc3f9807f42facde6334f36fe315/). After the changes in https://github.com/greenelab/manubot-rootstock/commit/0b58f448fa12a46d6c92a2dcef3551072df902f0 and deleting body and setting byrd's affiliations to `[]`, the following PDF was produced: [manuscript.pdf](https://github.com/greenelab/manubot-rootstock/files/2780137/manuscript.pdf).
> front-matter: omit null or empty author fields

- webpage/github-pandoc.css
- fix superscripts per [greenelab/meta-review#88 (comment)](https://github.com/greenelab/meta-review/pull/88#issuecomment-408546057)
- fix printing page margin css to be even `0.75in`
- hide hypothesis sidebar and tooltip on print
- fixed style from pandoc that made long/wide code boxes overflow past their container and look bad
> CSS improvements to github-pandoc.css 

- .travis.yml
- USAGE.md
- build/environment.yml
Updates weasyprint to v44, which may address
https://github.com/greenelab/manubot-rootstock/issues/173
> Update environment on 2019-01-31

- .travis.yml
From [these docs](https://docs.travis-ci.com/user/environment-variables/#default-environment-variables) of Travis environment variables:
> `TRAVIS_EVENT_TYPE`: Indicates how the build was triggered. One of `push`, `pull_request`, `api`, `cron`.
Previously, `ci/deploy.sh` could be run for `push`, `api`, or `cron` builds, but not for `pull_request` builds. This PR further restricts when deployment is run to just `push` builds.
See docs for [cron](https://docs.travis-ci.com/user/cron-jobs/) and [api](https://docs.travis-ci.com/user/triggering-builds/).
I don't think we want deployment after cron builds, since we're [thinking of](https://github.com/manubot/rootstock/pull/182#issuecomment-468182518) using cron builds to periodically test that rootstock continues to work with the latest …
> CI: only deploy on push TRAVIS_EVENT_TYPE

- content/01.abstract.md
- content/02.delete-me.md
- content/citation-tags.tsv
- content/metadata.yaml
Updated `delete-me.md` template to include a full list of `.html` and `.pdf` formatting elements we support in our themes. This includes headings, horizontal rules, images, tables, LaTeX, etc.
> Update delete-me.md with full list of available formatting elements

- build/themes/default.html
Added more background colors including white, darkgrey, and black. A white background can now be applied to a figure as `![an image](https://images.com/image.png){.white}`, and that class will be copied over to lightbox preview.
Added classes to align text/images/other elements horizontally, and align headers and a few other elements vertically in the page when printed.
Also changed the print styles a bit. Made the font size a standard 12pt, and the margins a standard 1in. Also changed the page break classes to a more cross-browser compatible value.
> Background colors, text/page alignment classes, print control styles

- build/plugins/accordion.html
- build/plugins/jump-to-first.html
- build/plugins/lightbox.html
- build/plugins/link-highlight.html
- build/plugins/table-of-contents.html
- build/plugins/tooltips.html
- build/themes/default.html
*Lightbox*
Changed the image copy procedure (copying `<img>` in document to lightbox `<img>`) from shallow (new `<img>` with same `src`) to deep copy (copy DOM node fully with all properties/attributes/styles, except for explicitly deleted ones like `width`, `height`, `id`, etc.).
*Tooltips*
Changed dimension styles a bit. Allowed tall tooltips to scroll vertically. Decreased spacing on nav bar.
*Table of Contents*
Allowed clicking off of the panel to close it, as expected on mobile.
> update lightbox tooltips and toc plugins

- build/plugins/table-of-contents.html
- build/themes/default.html
Fixes https://github.com/zach-hensel/low-noise-manuscript/commit/3ae5e37f79b31e06772a80a15ac00474d6d47330 and sets page margin back to `0.75in`.
> fix auto option in toc plugin, fix printing page margin

- build/plugins/table-of-contents.html
@zach-hensel Maybe you want to take a look at this since you caught the bug. I've changed the option name (because it applies to more than just whether the toc *starts* open or closed) and also the behavior a little bit.
I don't think we want to change the default to `'auto'` though, just to avoid cluttering the screen. Thoughts on this @dhimmel
> change auto open/close option functionality and comments

- build/themes/default.html
@dhimmel @slochower @agitter Per request (#192), I've made changes to the print CSS rules to reduce the number of pages when printing. This includes the following:
- smaller overall font size
- smaller line spacing
- smaller page margins (0.75in -> 0.5in)
- smaller heading margins
- smaller table cell padding
- smaller button icons
See the diff for more details.
Here's how it looks on the meta-review:
[meta-review.pdf](https://github.com/manubot/rootstock/files/3044822/meta-review.pdf)
> compactify print view

- build/webpage.py
Closes https://github.com/manubot/rootstock/issues/183
> webpage.py: note error in versions checkout is OK

- README.md
- USAGE.md
Closes #216 
I'm leaving the full citation in `USAGE.md` to help minimize confusion about what to cite in downstream manuscript instances.
> Add meta review link to readme

- build/build.sh
This PR is to address situations where the Electron renderer that Athena uses to produce PDFs crashes. There are at least two ways to avoid this: either by passing `--shm-size="2g"` to `docker run` or by mounting `/dev/shm`, both of which potentially work on Travis. The former has been tested on a personal repository and seems to alleviate the crashes.
Refs https://github.com/arachnys/athenapdf/issues/195
> Increase shared memory (--shm-size) to prevent athenapdf Docker from crashing

- build/assets/style.csl
This PR is based on the commit https://github.com/dhimmel/manubot-rootstock/commit/12b478389a2557aae3d1e941dd48a79cdd9507e1, which was suggested to me by @adam3smith at the FORCE 2019 conference. The original commit message is:
> Suggested by Sebastian Karcher to Daniel Himmelstein at the FORCE2018 Conference. Not yet tested.  The changes focus on dealing with the missing space when authors are missing and showing editors.
I think it is possible these changes will resolve https://github.com/manubot/rootstock/issues/218. However, I want to test them some and read more of the CSL doc to understand what they do.
> Suggested CSL Style changes by Sebastian Karcher

- build/build.sh
Also move to recommended quoted $() instead of backticks.
Fixes manubot/rootstock#229
> Fix `DOCKER_EXISTS` setting so it doesn't fail when docker missing.

- build/README.md
It is not intuitive that the latest rootstock is not compatible with the latest Manubot Python package release.  This makes the dependencies more explicit.
Closes #228 (if we all agree this is sufficient to close the issue).
> Add manubot version details to build readme

- .travis.yml
- README.md
- build/README.md
- build/autobuild.sh
- build/build.sh
- ci/deploy.sh
Writing good shell scripts that provide useful debugging information seems to be challenging. This PR attempts to adopt best practices as [discussed here](https://kvz.io/blog/2013/11/21/bash-best-practices/).
@dongbohu @michaelmhoffman @agitter feel free to suggest any other ways our shell scripts could be improved.
> Harden shell scripts with improved robustness & verbosity

- README.md
- build/README.md
Some of the documentation about the local build script had not been updated for a while.  @sbonaretti would these updates help address the undocumented behavior that led to your questions in #237?
Closes #237
> Improve documentation about build process

- USAGE.md
Closes #242 
This may end up being a placeholder until we have more permanent documentation.
Should we remove the list of example manuscripts here and focus on maintaining the catalog?
> Add customization instructions and catalog to USAGE

- .travis.yml
Failures in after_success did not cause the entire build to fail.
Now if deployment fails, the build should fail.
References:
https://docs.travis-ci.com/user/deployment/#conditional-releases-with-on
https://docs.travis-ci.com/user/deployment/script/
https://github.com/travis-ci/travis-ci/issues/758
> Travis CI: replace after_success with deploy stage

- ci/deploy.sh
Specify `--no-jekyll` to add a `.nojekyll` file to the `gh-pages` branch.
Manubot does not make use of Jekyll to do additional processing of webpage content hosted on GitHub Pages. Disable Jekyll to bypass an unnecessary CI job, which can slow down webpage deployment. https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
> Disable Jekyll processing on GitHub Pages

- build/build.sh
- build/plugins/math.html
This PR disables MathJax's fast-preview option and increases the Athena print delay in response to #252.
Here's what it looks like now to load equations:
You can briefly see some gray text, which I believe is just the plain text of the latex input. It's then replaced by an SVG when it's ready.
It looks like there is a brief moment where the both the gray text and the svg is there. So I guess even with this change, it's possible that equations could still be doubled if the timer for pdf output is not long enough.
http://docs.mathjax.org/en/latest/options/extensions/fast-preview.html
> disable mathjax fast preview

- build/environment.yml
- ci/install.sh
- content/00.front-matter.md
Follows up on https://github.com/manubot/rootstock/pull/262#issuecomment-519944443
Refs https://github.com/manubot/rootstock/issues/198
> Use AppVeyor artifact URLs in manuscript front-matter

- build/themes/default.html
- content/02.delete-me.md
This has been bugging me for a while:
Long links that can't break at a "natural" language point -- like links that have a lot of numbers I guess, it's dependent on the browser -- cause overflow to the right of the body/paper element.
I remember that I had previously had `word-break: break-all` for links, but that was causing them to break at unnatural points, like in between words, so we took it out, not remembering why it was there in the first place.
This PR adds it back in, but with `break-word`, which forces line breaks for long number links, but should also try to break them at natural points first.
___
Just to be sure, tested that it breaks at words:
> fix link overflow

- README.md
- build/autobuild.sh
- webpage/README.md
Cleans up remaining mentions of `python build/webpage.py` to the new method `manubot webpage` -- continuing the transition from https://github.com/manubot/rootstock/pull/265
> python webpage.py -> manubot webpage

- build/build.sh
Closes https://github.com/manubot/rootstock/issues/270
The existence of two common pagesizes for physical paper, A4 and Letter, creates user confusion. Sometimes users print a PDF with A4 dimensions onto Letter paper and do not use the "scale to fit" printer setting. This leads to truncated text at the bottom of the page. Ultimately, it is not a Manubot issue, but confuses Manubot users nonetheless.
When exporting the HTML to PDF Manubot uses an A4 pagesize, which while less common in the U.S. is an international standard. This commit explicitly specifies the default behavior, such that there is no functional change. However, by specifying the pagesize, its more clear to Manubot users where pagesize gets set. This will hopefully spare users extra debugging.
If manuscript viewers would …
> Explicitly specify PDF pagesize

- USAGE.md
- build/environment.yml
- content/metadata.yaml
metadata.yaml should now use `authors` instead of `author_info`.
Update USAGE to mention delete-me.
> Update metadata.authors & USAGE

- .github/workflows/manubot.yaml
look into addressing https://github.com/czbiohub/orthology-free-comparative-transcriptomics-paper/pull/41#issuecomment-579419055
> Attempt to version artifacts

- SETUP.md
Found myself having trouble navigating the setup.md file and wanting a table of contents (TOC)
Autogenerated by https://ecotrust-canada.github.io/markdown-toc/
> Add table of contents to SETUP.md

- .github/workflows/manubot.yaml
- SETUP.md
- ci/deploy.sh
Evaluates whether we can use `secrets.GITHUB_TOKEN` for deployment. Testing the PR in the repository https://github.com/dhimmel/rootstock-github-token.
Also noting https://github.com/dhimmel/rootstock-actions-deploy to test using [`peaceiris/actions-gh-pages`](https://github.com/peaceiris/actions-gh-pages). However, I think that using our existing `deploy.sh` is less disruptive for now.
> GH Actions: no setup deployment using GITHUB_TOKEN

- .github/workflows/manubot.yaml
It looks like GitHub actions was also running on my fork. Now GitHub Actions deploys even without a manually set SSH Key. Therefore, it [tried to deploy on my fork](https://github.com/dhimmel/manubot-rootstock/commit/d14dd7dc8503fdae86c1a5f66777b62e11a0ebc6/checks?check_suite_id=465620679#step:7:17).
> Do not deploy forked repositories

- SETUP.md
- ci/deploy.sh
Prototyped in https://github.com/dhimmel/rootstock-branchless-setup
BTW I had some trouble initially having GITHUB_TOKEN deploy in https://github.com/dhimmel/rootstock-branchless-setup but I played around in settings and now it works I think. Must look into more
> Simplify setup by creating branches later

- ci/deploy.sh
I noticed some of the automatically generated URLs are broken at https://github.com/manubot/rootstock/tree/gh-pages
My best guess is that these need to be exported before calling `envsubst`.  The exported variables are substituted correctly.
> Export environment variables needed for gh-pages readme

- USAGE.md
- build/environment.yml
- content/00.front-matter.md
- content/metadata.yaml
closes https://github.com/manubot/rootstock/issues/329
upgrade manubot with author.funders processing added in
https://github.com/manubot/manubot/commit/9c33b7a53f60aa5aba42424b925af0c32ea561fb
> metadata: use list for author.funders

- .appveyor.yml
- .travis.yml
- USAGE.md
- build/assets/custom-dictionary.txt
- build/build.sh
- ci/install.sh
References https://github.com/manubot/manubot/issues/31
Initial implementation from https://github.com/agitter/my-manuscript/pull/15
There are a few open questions to discuss:
I've noticed that many spelling errors come from `00.front-matter.md`.  We could automatically add all of the manuscript metadata to the custom dictionary, but then we would ignore typos in affiliations or titles.  I would prefer to save that for a separate pull request even if we do want it.
> Enable pandoc spellcheck filter

- USAGE.md
closes https://github.com/manubot/rootstock/issues/334
> USAGE: howto set citation style using pandoc defaults

- USAGE.md
- build/environment.yml
- content/02.delete-me.md
todo:
merges https://github.com/manubot/rootstock/pull/342
Includes major updates to how citations are processed by the pandoc-manubot-cite filter.
See the following commit messages for more information:
- https://github.com/manubot/manubot/commit/7055bcc6524fdf1ef97d838cf0158973e2061595
- https://github.com/manubot/manubot/commit/47b03e0c202e6a0561e6548ba08a4ad790f56eee
Removes requirement to prefix certain citekeys with raw: or tag:
Removes support for deprecated `content/citation-tags.tsv`.
Switches from tag to alias terminology for citation aliases. 
closes https://github.com/manubot/manubot/issues/120
Removes pandas and jsonref dependencies, which are no longer needed.
> Update manubot for more flexible citation processing

- build/plugins/hypothesis.html
- build/plugins/table-of-contents.html
- build/themes/default.html
- content/02.delete-me.md
closes https://github.com/manubot/rootstock/issues/306
closes https://github.com/manubot/rootstock/issues/293
closes https://github.com/manubot/rootstock/issues/280
closes https://github.com/manubot/rootstock/issues/281 
- changes default font sizes of h1 through h6 to be larger than base text size, breaking with browser precedent
- fixes overlap of hypothesis sidebar and table of contents plugin on small screens
- adds button to load hypothesis plugin, rather than automatically loading it
> fix some hypothesis issues

- build/assets/style.csl
Afaik, display elements don't work properly with pandoc, so I don't think the block elements will do anything for you. citeproc-js isn't happy with those two blocks in there.
> Add a space delimiter across the style

- USAGE.md
My recollection is that `pandoc-fignos` (and/or `pandoc`?) requires a line of whitespace before a figure.  This isn't currently documented.
> Update figure usage instructions

- .github/workflows/manubot.yaml
From https://github.com/manubot/rootstock/runs/1212860980#step:2:10:
> Warning: The `set-env` command is deprecated and will be disabled soon.
> Please upgrade to using Environment Files.
> For more information see:
> https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#setting-an-environment-variable
> GitHub Actions: use Environment Files not set-env

- build/plugins/table-of-contents.html
Closes #369 
- split auto-open/close table of contents plugin options into two separate options
- fix bug where toc panel closes when tapped on touch screen before toc link click can be registered
> change toc behavior and fix mobile click bug

- build/pandoc/defaults/html.yaml
- build/plugins/d3.html
- build/plugins/inline-svg.html
- build/plugins/math.html
- build/themes/default.html
- adds plugin to "inline" svg img's (finds <img> tags with .svg src's, and replaces them in-place with the text source content of the svg)
- adds d3 plugin
- adds hash and other security attributes to mathjax plugin
Supercedes #373
A few notes:
- this wont work on local copies due to cross origin, but should fail gracefully, and not change the `<img>` if it can't load the source text. to test this PR, you'll have to run a local server, either with [the manubot commands](https://github.com/manubot/rootstock#local-execution) or this handy [chrome app](https://chrome.google.com/webstore/detail/web-server-for-chrome/ofhbbkphhbklhfoeikjpcbhemlocgigb/related?hl=en) 
- i've split these into two separate plugins, because they're really two separate concerns
- inserting the d3 script with …
> Add "inline svg" and "d3" plugins

- .github/workflows/manubot.yaml
closes https://github.com/manubot/rootstock/issues/388
> The `set-env` command is deprecated and will be disabled on
November 16th. Please upgrade to using Environment Files.
For more information see:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> CI: upgrade to conda-incubator/setup-miniconda@v2

- USAGE.md
- build/environment.yml
refs https://github.com/manubot/manubot/issues/123
> infer citekey prefixes

- build/pandoc/defaults/html.yaml
- build/plugins/scite.html
- removed css include (scite authors recently pushed update that includes the css in the js)
- remove vestigial `onscroll` cruft
- add js "media query" check to abort the script when printing (though it doesn't work in athena, it should work it whatever we switch to). this can prevent timeouts in contexts like appveyor where it seems to wait forever for the scite lookups to return
- add css to hide badges on print (should work in athena, but js still runs)
> update scite plugin

- SETUP.md
- setup.bash
I wanted to make a couple of manuscript repos and also wanted it to be as easy as possible to convince the rest of my team that this is the tool we should use to write papers, so I wrote a setup script. 
It takes the "Intermediate step" from #401 where the users manually create an empty repo and the script does the rest. 
This seems the most user-friendly route, even if it is not the most automated.
> Setup script

- SETUP.md
> Add "gh repo create" to SETUP.md

- build/plugins/accordion.html
- build/plugins/attributes.html
- build/plugins/hypothesis.html
- build/plugins/scite.html
Make a few minor fixes learned from https://github.com/greenelab/covid19-review/pull/1036
- add ability to collapse heading 2 section by default using attributes plugin
- run attributes plugin before other plugins to ensure the above works, and to possibly prevent future errors
- locally scope hypothesis and scite plugin scripts
> add ability to collapse section by default, prioritize attr plugin load

- USAGE.md
- build/environment.yml
Switches CURIE support and resolution from the Identifiers.org
database to the Bioregistry, which is open source and community
curated.
See https://github.com/manubot/manubot/commit/0205bd6c10d81d40d51989e23c04d8d68214ba47
> Upgrade manubot package for Bioregistry support

- build/build.sh
closes https://github.com/manubot/rootstock/issues/440
`MANUBOT_USE_DOCKER=true` instructs Manubot to use Docker for PDF export. Defaults to `DOCKER_RUNNING` (whether Docker is running on the system).
> build: MANUBOT_USE_DOCKER environment variable

- build/build.sh
closes https://github.com/manubot/rootstock/issues/451
The `,,` operator was introduced in bash 4.0, but bash on macOS is still version 3.2
> build.sh: remove bash lowercase substitution

- .github/workflows/manubot.yaml
- ci/install.sh
This PR switches from the miniconda to miniforge installer for both GitHub Actions and AppVeyor. The difference between these installers [is](https://conda-forge.org/):
> Miniforge is an effort to provide Miniconda-like installers, with the added feature that conda-forge is the default channel. Unlike Miniconda, these support ARMv8 64-bit (formally known as `aarch64`).
I've always found using `conda-forge` as the default channel to be preferable. conda-forge is a community maintained project aligned with the ethos of manubot.
[Miniforge](https://github.com/conda-forge/miniforge) also makes it easy to switch to `mamba` instead of `conda` for installation should we want in the future.
> CI: use miniforge instead of miniconda

- .github/workflows/manubot.yaml
Updates method added in https://github.com/manubot/rootstock/pull/399. See commit notes from https://github.com/manubot/rootstock/pull/399/commits/667d170eb2f1898156226456292d25c1c99377c4 on references for the old method. I believe `github.event.repository.default_branch` did not exist when we initially implemented this.
One benefit is this removes a bash command that does not work on macos due to an old grep. Running CI on macos or windows is helpful for prototyping our environment.
- https://stackoverflow.com/a/68414395/4651668
> CI: use github.event context for DEFAULT_BRANCH

- build/environment.yml
DataCite content negotiation is no longer used directly for DOIs. DOI metadata resolution should experience fewer failures, but certain fields might experience regressions.
> Upgrade manubot & pandoc on 2022-01-24

- USAGE.md
- content/00.front-matter.md
- content/metadata.yaml
> Indicate Corresponding Author / Review Commons Compatibility

- content/00.front-matter.md
This PR adds a small change in front-matter to fix the author list when no author metadata (ORCID, Github, Twitter, etc) is given for an author. Below, I show an example of the current code and problem in [this manuscript](https://greenelab.github.io/phenoplier_manuscript/):
As you can see, when metadata is no present for an author, an unnecessary line break is added leaving an empty blank line.
This PR fixes this, producing this output:
> Fix author list when no author metadata is present

- build/environment.yml
- content/02.delete-me.md
This PR is related to issue #488. It adds `librsvg` as a dependency so pandoc converts SVG images to a format supported by Word (`.docx`).
I think this was not introduced here, but when I build the rootstock manuscript with `BUILD_DOCX=true`, opening the docx file with OpenOffice Writer shows this error:
Clicking on "yes" allows to open the document. However, the SVG file (`vector.svg`) is not shown in the Word document. This is fixed if the file is downloaded and referenced locally. I thought it might be important to mention how to do this in the documentation, so I also added a note about this.
> Add librsvg as dependency

- .github/workflows/ai-revision.yaml
Closes #492
I'm not sure whether additional changes are needed for the draft pull request issue once write permissions are enabled. Line 68 already sets `draft: true`.
> Set write permissions in AI workflow

- setup.bash
This fixes typos and also switches to the US English spelling of "organization".
> Setup script typos

- .github/workflows/ai-revision.yaml
- USAGE.md
This PR 1) improves the documentation about section mapping, and 2) adds another field in the `ai-revision` workflow run dialog to provide a custom prompt and document their use.
This PR is linked to [this another PR](https://github.com/manubot/manubot-ai-editor/pull/18) in manubot/manubot-ai-editor.
> Add documentation about section mapping and types of prompts

- .appveyor.yml
refs https://github.com/manubot/rootstock/issues/508
> CI: appveyor use ubuntu 22.04

- .github/workflows/ai-revision.yaml
This PR simply updated the LLM to `gpt-3.5-turbo` since `text-davinci-003` is now deprecated.
> AI-revision: change default model to GPT 3.5 Turbo

- .github/workflows/ai-revision.yaml
- .github/workflows/manubot.yaml
closes https://github.com/manubot/rootstock/issues/515
Major version upgrades of dependent actions for node 20 support.
> github action dependency upgrades on 2024-07-31

- .github/workflows/manubot.yaml
Removing the explicitly set `Mambaforge` variant and the call to `use-mamba` took care of an error preventing GitHub Actions to build a manuscript of mine during the so-called 'brownout days' stated in https://conda-forge.org/news/2024/07/29/sunsetting-mambaforge/
I might not see all the consequences of simply deleting those details, but submit this nonetheless as a PR :)
Fixes #519
> Remove explicitly set `mamba`-stuff from workflow file

- build/README.md
- ci/install-spellcheck.sh
- ci/install.sh
closes https://github.com/manubot/rootstock/issues/519
> replace all mambaforge with miniforge
